import assert from 'node:assert/strict';
import fs from 'node:fs';
import {fromDesign,run,execute} from './runner.mjs';
const d={width:12,depth:10,height:5,sampleDistance:.3,floor:{thickness:200,material:'Concrete'},ceiling:{thickness:200,material:'Concrete'},workload:500,energy:6,gantry:0,fieldX:20,fieldY:40,isocentreHeight:1.3,isoOffsetX:0,isoOffsetZ:-1.6,items:[{id:'wall',name:'Wall',kind:'Wall',x:6,z:0,y:0,length:10,angle:90,shielding:{thickness:150,material:'Concrete'}},{id:'linac',name:'LINAC',kind:'LINAC',x:-2,z:1,y:0,angle:90},{id:'desk',name:'Workstation',kind:'Desk',x:8.5,z:-3,y:0,assessmentHeight:1.2,occupancy:.25,isControlled:false}],regions:[]};
const r=fromDesign(d);
const withCustom=structuredClone(d);withCustom.items.push({id:'custom-wall',kind:'Component',component:{type:'Trapezoid'}});
assert.throws(()=>run(withCustom),/Custom component geometry is not supported/,'custom shielding geometry must not silently disappear from QA');
assert.throws(()=>execute(withCustom,'export'),/Custom component geometry is not supported/,'canonical export must not silently discard custom shapes');
assert.equal(r.equipment[0].workload,50000);
assert.equal(r.floor.thickness,200);
assert.equal(r.equipment[0].x,2.4);
assert.equal(r.equipment[0].y,6);
assert.equal(r.equipment[0].planRotationDegrees,270);
assert.equal(r.equipment[0].linacFieldSizeCm,80/3);
assert.equal(r.walls[0].y1,10);
assert.equal(r.walls[0].y2,0);
assert.equal(r.workstations[0].isControlled,false);
const report=run(d);
const markers=structuredClone(d);markers.ct={version:1,sources:[],results:[]};markers.items.push({id:'roi',kind:'Model',model:'Dot',ctPoint:{version:1,role:'ROI'},x:3,y:1,z:0});
assert.deepEqual(run(markers).rows,report.rows,'point annotations do not alter legacy QA geometry');
assert.throws(()=>execute(markers,'export'),/CT points.*no records were discarded/,'canonical export must not lose CT metadata');
const ctSources=structuredClone(markers);ctSources.ct.sources.push({id:'ct-source'});
assert.throws(()=>run(ctSources),/dedicated CT ROI engine/,'CT sources cannot receive LINAC QA verdicts');
const disabled=structuredClone(d);disabled.items[0].shielding.shieldingEnabled=false;
assert.throws(()=>run(disabled),/Disabled CT shielding/,'disabled shielding must not be silently enabled for reference QA');
assert.throws(()=>execute(disabled,'export'),/Disabled CT shielding/,'disabled shielding export rejected');
const plateGlass=structuredClone(d);plateGlass.items[0].shielding.material='PlateGlass';
assert.throws(()=>run(plateGlass),/not the legacy lead-glass fit/,'plate glass cannot inherit lead-glass attenuation');
const protectedDesign=structuredClone(d);for(const item of protectedDesign.items){item.locked=true;item.groupId='protected';item.transparency=.5;}
assert.deepEqual(fromDesign(protectedDesign),r,'native protection metadata is excluded from canonical projection');
assert.deepEqual(run(protectedDesign).rows,report.rows,'native protection metadata does not change QA');
assert.ok(report.rows.length>0);
assert.ok(report.rows.every(x=>Number.isFinite(x.shieldedAirKerma)));
const canonical=run({room:r});
assert.deepEqual(report.rows,canonical.rows);
const twice=structuredClone(d);twice.workload*=2;
const doubleReport=run(twice);
for(let i=0;i<report.rows.length;i++)assert.ok(Math.abs(doubleReport.rows[i].shieldedAirKerma-2*report.rows[i].shieldedAirKerma)<1e-10);
const empty=structuredClone(r);empty.workstations=[];
assert.equal(run(empty).rows.length,0);
assert.match(run(empty).summary,/No compliance conclusion/);
fs.writeFileSync(new URL('./example-design.json',import.meta.url),JSON.stringify(d,null,2));
fs.writeFileSync(new URL('./golden-report.json',import.meta.url),JSON.stringify(report,null,2));
console.log('PASS: workload, mm units, centered origin, yaw, rotated isocentre, equivalent field, wall endpoints, controlled-area flag, populated finite QA, canonical room parity, workload scaling, empty occupancy.');
